### PR TITLE
Fix: api cleanup fixes

### LINKED ISSUE #67: Change licence_no from int to str

### PR DESCRIPTION
**Pull request by anatolegosset**
Fix #67 #65 #64 #62 #61 #60 #55 #54

### CODE REVIEW

File: admin/static/admin_show_all_players.js [hunk 1]
```diff
@@ -160,8 +169,9 @@ function filterData() {
     let cellValue;
```
Comment (layceline) [inline admin/static/admin_show_all_players.js:169]: is this useful? it occurs twice

**Review by layceline — CHANGES_REQUESTED** [review]
